resources:
  - ../../base
namespace: dev
patches:
  - path: patch.yaml

images:
  - name: heahaidu/springboot-health-bootstrap
    newTag: "1.21"

labels:
  - pairs:
      app: backend
    includeSelectors: true
  - pairs: 
      team: dev
    includeSelectors: false
    includeTemplates: true
commonAnnotations:
  app: test

# configMapGenerator:
#   - name: spring-configmap
#     env: config.properties

# config.properties
# ENV=