resources:
  - ../../base
namespace: dev
patches:
  - path: patch.yaml

images:
  - name: heahaidu/springboot-health-bootstrap
    newTag: "1.2"

labels:
  - pairs:
      app: spring
      team: dev
    includeSelectors: true