apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-health-check
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: springboot-health-check
  template:
    spec:
      containers:
        - name: springboot-health-check
          image: heahaidu/springboot-health-bootstrap:1.2
          env:
            - name: APP_ENV
              value: dev